package org.apache.avro;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.junit.Rule;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Map;

import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class SchemaParserWhiteBoxTest {

  private Schema.Parser parser;

  @Rule
  public TemporaryFolder tempFolder = new TemporaryFolder();

  @Before
  public void setUp() {
    parser = new Schema.Parser();
  }

  @After
  public void tearDown() {
    parser = null;
  }

  //Verifico corretto funzionamento del parse(File)
  @Test
  public void TC41_parseFromFile() throws IOException {
    // creo un file temporaneo che deve contenere uno schema AVRO e da ricerche lo standard di questo tipo di file è .avsc
    File schemaFile = tempFolder.newFile("test_schema.avsc");
    //scrivo il schema json
    String jsonContent = "{\"type\": \"record\", \"name\": \"FileTest\", \"fields\": []}";
    //per scrivere nel file devo avere una array di byte e non una stringa, uso quindi getBytes. La specifica inoltre riporta
    //che un input schema valido è in formato UTF_8
    Files.write(schemaFile.toPath(), jsonContent.getBytes(StandardCharsets.UTF_8));

    // chiamo il metodo
    Schema schema = parser.parse(schemaFile);

    assertNotNull(schema);
    assertEquals("FileTest", schema.getName());
  }
  //verifico corretto funzionamento del metodo parse(inputStream)
  @Test
  public void TC42_parseFromInputStream() throws IOException {
    //trasformo la stringa in byte e la avvolgo in un ByteArray
    String jsonContent = "{\"type\": \"record\", \"name\": \"StreamTest\", \"fields\": []}";
    ByteArrayInputStream inputStream = new ByteArrayInputStream(jsonContent.getBytes(StandardCharsets.UTF_8));

    Schema schema = parser.parse(inputStream);

    assertNotNull(schema);
    assertEquals("StreamTest", schema.getName());
  }

  @Test
  public void TC43_verifyGetTypesAndNamesCache() {
    // Definisco uno schema fixed con name = MD5 ed eseguo il parse
    String json = "{\"type\": \"fixed\", \"name\": \"MD5\", \"size\": 16}";
    parser.parse(json);
    // ora quindi questo schema definito come una stringa è stato salvato nell oggetto Names names che funge da memoria

    // chiamo il metodo getTypes
    Map<String, Schema> types = parser.getTypes();

    assertNotNull(types);
    assertTrue("La mappa dei tipi deve contenere MD5", types.containsKey("MD5"));
    assertEquals(Schema.Type.FIXED, types.get("MD5").getType());
  }

  // Verifica Metodi Getter e Setter
  @Test
  public void TC44_verifyGetValidate() {
    // Default è true
    assertTrue(parser.getValidate());

    parser.setValidate(false);
    assertFalse(parser.getValidate());
  }

 // ho rimosso il 05 perche era uguale ad uno che avevo già testato, chiedi del 6 7 8 a gemini e vedi se sono come quelli che hai già fatto
  // Testo che il valore di default passato se non è ammesso non venga accettato
  // la riga if (enumDefault != null && !symbols.contains(enumDefault))
  @Test
  public void TC45_enumDefaultNotInSymbols() {

    String json = "{" +
      "\"type\": \"enum\", " +
      "\"name\": \"Status\", " +
      "\"symbols\": [\"OPEN\", \"CLOSED\"], " +
      "\"default\": \"UNKNOWN\"" +
      "}";

    assertThrows(SchemaParseException.class, () -> {
      parser.parse(json);
    }, "deafult non ammette il valore passato");
  }
  //verifico che passando un json in cui la proprietà logical type è messa nel posto sbagliato, venga ignorata
  @Test
  public void TC46_logicalTypeDefinedInFieldInsteadOfType() {
    // errore: logicalType dovrebbe essere dentro "type"
    String json = "{" +
      "\"type\": \"record\", " +
      "\"name\": \"WarnTest\", " +
      "\"fields\": [" +
      "  {\"name\": \"f1\", \"type\": \"int\", \"logicalType\": \"date\"}" +
      "]" +
      "}";

    Schema schema = parser.parse(json);
    assertNotNull(schema);
    // verifico che il logical type non sia stato applicato (perché posizionato male)
    assertNull(schema.getField("f1").schema().getLogicalType());
  }

  // test un tipo fixed in cui la size è presente ma la passo come stringa invece che intero
  @Test
  public void TC47_fixedSizeNotInteger() {
    // nel codice: if (sizeNode == null || !sizeNode.isInt())
    String json = "{\"type\": \"fixed\", \"name\": \"BadFixed\", \"size\": \"16\"}"; // size come stringa

    assertThrows(SchemaParseException.class, () -> {
      parser.parse(json);
    }, "la size non può essere una stringa");
  }

  //Generated by LLM

  @Test
  public void TC48_parseWithNamespaceHandling() {
    // Questo esercita la logica di salvataggio e ripristino del namespace
    // all'interno del metodo parse(JsonNode, Names)

    String json = "{" +
      "\"type\": \"record\", " +
      "\"name\": \"Outer\", " +
      "\"namespace\": \"com.example\", " +
      "\"fields\": [" +
      "   {\"name\": \"inner\", \"type\": { \"type\": \"record\", \"name\": \"Inner\", \"fields\": [] } }" +
      "]" +
      "}";

    Schema schema = parser.parse(json);
    assertEquals("com.example.Outer", schema.getFullName());
    // Inner dovrebbe ereditare il namespace
    assertEquals("com.example.Inner", schema.getField("inner").schema().getFullName());
  }
}
