package org.apache.avro;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.junit.Rule;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Map;

import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class SchemaParserWhiteBoxTest {

  private Schema.Parser parser;

  @Rule
  public TemporaryFolder tempFolder = new TemporaryFolder();

  @Before
  public void setUp() {
    parser = new Schema.Parser();
  }

  @After
  public void tearDown() {
    parser = null;
  }

  //Verifico corretto funzionamento del parse(File)
  @Test
  public void TC41_parseFromFile() throws IOException {
    // creo un file temporaneo che deve contenere uno schema AVRO e da ricerche lo standard di questo tipo di file è .avsc
    File schemaFile = tempFolder.newFile("test_schema.avsc");
    //scrivo il schema json
    String jsonContent = "{\"type\": \"record\", \"name\": \"FileTest\", \"fields\": []}";
    //per scrivere nel file devo avere una array di byte e non una stringa, uso quindi getBytes. La specifica inoltre riporta
    //che un input schema valido è in formato UTF_8
    Files.write(schemaFile.toPath(), jsonContent.getBytes(StandardCharsets.UTF_8));

    // chiamo il metodo
    Schema schema = parser.parse(schemaFile);

    assertNotNull(schema);
    assertEquals("FileTest", schema.getName());
  }
  //verifico corretto funzionamento del metodo parse(inputStream)
  @Test
  public void TC42_parseFromInputStream() throws IOException {
    //trasformo la stringa in byte e la avvolgo in un ByteArray
    String jsonContent = "{\"type\": \"record\", \"name\": \"StreamTest\", \"fields\": []}";
    ByteArrayInputStream inputStream = new ByteArrayInputStream(jsonContent.getBytes(StandardCharsets.UTF_8));

    Schema schema = parser.parse(inputStream);

    assertNotNull(schema);
    assertEquals("StreamTest", schema.getName());
  }

  @Test
  public void TC43_verifyGetTypesAndNamesCache() {
    // Definisco uno schema fixed con name = MD5 ed eseguo il parse
    String json = "{\"type\": \"fixed\", \"name\": \"MD5\", \"size\": 16}";
    parser.parse(json);
    // ora quindi questo schema definito come una stringa è stato salvato nell oggetto Names names che funge da memoria

    // chiamo il metodo getTypes
    Map<String, Schema> types = parser.getTypes();

    assertNotNull(types);
    assertTrue("La mappa dei tipi deve contenere MD5", types.containsKey("MD5"));
    assertEquals(Schema.Type.FIXED, types.get("MD5").getType());
  }

  // Verifica Metodi Getter e Setter
  @Test
  public void TC44_verifyGetValidate() {
    // Default è true
    assertTrue(parser.getValidate());

    parser.setValidate(false);
    assertFalse(parser.getValidate());
  }

 // ho rimosso il 05 perche era uguale ad uno che avevo già testato, chiedi del 6 7 8 a gemini e vedi se sono come quelli che hai già fatto
  // Testo che il valore di default passato se non è ammesso non venga accettato
  // la riga if (enumDefault != null && !symbols.contains(enumDefault))
  @Test
  public void TC45_enumDefaultNotInSymbols() {

    String json = "{" +
      "\"type\": \"enum\", " +
      "\"name\": \"Status\", " +
      "\"symbols\": [\"OPEN\", \"CLOSED\"], " +
      "\"default\": \"UNKNOWN\"" +
      "}";

    assertThrows(SchemaParseException.class, () -> {
      parser.parse(json);
    }, "deafult non ammette il valore passato");
  }
  //verifico che passando un json in cui la proprietà logical type è messa nel posto sbagliato, venga ignorata
  @Test
  public void TC46_logicalTypeDefinedInFieldInsteadOfType() {
    // errore: logicalType dovrebbe essere dentro "type"
    String json = "{" +
      "\"type\": \"record\", " +
      "\"name\": \"WarnTest\", " +
      "\"fields\": [" +
      "  {\"name\": \"f1\", \"type\": \"int\", \"logicalType\": \"date\"}" +
      "]" +
      "}";

    Schema schema = parser.parse(json);
    assertNotNull(schema);
    // verifico che il logical type non sia stato applicato (perché posizionato male)
    assertNull(schema.getField("f1").schema().getLogicalType());
  }

  // test un tipo fixed in cui la size è presente ma la passo come stringa invece che intero
  @Test
  public void TC47_fixedSizeNotInteger() {
    // nel codice: if (sizeNode == null || !sizeNode.isInt())
    String json = "{\"type\": \"fixed\", \"name\": \"BadFixed\", \"size\": \"16\"}"; // size come stringa

    assertThrows(SchemaParseException.class, () -> {
      parser.parse(json);
    }, "la size non può essere una stringa");
  }

  //Generated by LLM

  @Test
  public void TC48_parseWithNamespaceHandling() {
    // Questo esercita la logica di salvataggio e ripristino del namespace
    // all'interno del metodo parse(JsonNode, Names)

    String json = "{" +
      "\"type\": \"record\", " +
      "\"name\": \"Outer\", " +
      "\"namespace\": \"com.example\", " +
      "\"fields\": [" +
      "   {\"name\": \"inner\", \"type\": { \"type\": \"record\", \"name\": \"Inner\", \"fields\": [] } }" +
      "]" +
      "}";

    Schema schema = parser.parse(json);
    assertEquals("com.example.Outer", schema.getFullName());
    // Inner dovrebbe ereditare il namespace
    assertEquals("com.example.Inner", schema.getField("inner").schema().getFullName());
  }
  //fino a ora ho testato che i record venissero parsati correttamente, con questo test verifico che anche le proprietà extra vengano salvate
  @Test
  public void TC49_VerifyExtraPropertyAreSaved() {
    // definisco un record con una proprietà custom "extraProp" nel field di nome "f"
    String json = "{\"type\":\"record\",\"name\":\"Rec\",\"fields\":[{\"name\":\"f\",\"type\":\"int\",\"extraProp\":\"valore\"}]}";
    //eseguo il parse
    Schema schema = parser.parse(json);

    // verifico che la proprietà sia stata salvata
    assertEquals("valore", schema.getField("f").getProp("extraProp"));
  }

  //verifico che l enum che parso venga riutilizzato correttamente
  @Test
  public void TC50_VeryReuseEnumJustDefined() {
    // definisco un enum "MyEnum" e poi lo riuso come tipo per il campo "f2"
    String json = "{" +
      "\"type\": \"record\", \"name\": \"Container\", " +
      "\"fields\": [" +
      "  {\"name\": \"f1\", \"type\": {\"type\": \"enum\", \"name\": \"MyEnum\", \"symbols\": [\"A\"]}}," +
      // qui faccio riferimento a MyEnum
      "  {\"name\": \"f2\", \"type\": \"MyEnum\"}" +
      "]" +
      "}";

    Schema schema = parser.parse(json);
    assertNotNull(schema);
    assertEquals(Schema.Type.ENUM, schema.getField("f2").schema().getType());
  }

  //Verifico che quando il parser entra in un record annidato che ha un namespace diverso, alla fine del parsing venga
  //ripristinato il namespace precedente, Generated by LLM
  @Test
  public void TC51_VerifyReturnBackContext() {
    // "Outer" è in "com.example". Inner cambia namespace a "com.other".
    // Il campo "f2" usa un tipo "Local". Poiché è definito in Outer,
    // ci aspettiamo che il suo full name sia "com.example.Local".
    // Se il namespace non viene ripristinato dopo Inner, "f2" diventerebbe "com.other.Local".
    String json = "{" +
      "\"type\": \"record\", \"name\": \"Outer\", \"namespace\": \"com.example\", " +
      "\"fields\": [" +
      "  {\"name\": \"f1\", \"type\": {\"type\": \"record\", \"name\": \"Inner\", \"namespace\": \"com.other\", \"fields\": []} }," +
      "  {\"name\": \"f2\", \"type\": {\"type\": \"fixed\", \"name\": \"Local\", \"size\": 1} }" +
      "]" +
      "}";

    Schema schema = parser.parse(json);

    Schema f2Schema = schema.getField("f2").schema();
    // Verifico che il namespace sia tornato a "com.example.Local"
    assertEquals("com.example.Local", f2Schema.getFullName());
  }


  // Verifico che un default value di tipo double passato come Stringa venga convertito
  @Test
  public void TC52_killMutant17241_DoubleDefaultAsString() {
    String json = "{" +
      "\"type\": \"record\", " +
      "\"name\": \"FloatTest\", " +
      "\"fields\": [" +
      "  {\"name\": \"f\", \"type\": \"double\", \"default\": \"3.14\"}" +
      "]" +
      "}";

    Schema schema = parser.parse(json);

    // recupero il valore di default.
    Object defaultVal = schema.getField("f").defaultVal();
    // Verifico che il valore sia stato convertito in un numero
    assertTrue("Il default dovrebbe essere un numero", defaultVal instanceof Number);
    assertEquals(3.14, ((Number) defaultVal).doubleValue(), 0.001);
  }


  // Verifico il riferimento a un tipo esistente tramite un oggetto JSON
  @Test
  public void TC51_killMutant17771_ReferenceAsJsonObject() {
    // definisco un tipo "Shared"
    String sharedDef = "{\"type\": \"fixed\", \"name\": \"Shared\", \"size\": 16}";
    parser.parse(sharedDef);

    // Uso "Shared" dentro un record, normalmente si scrive "type": "Shared" ma ora verifio che
    // "type": { "type": "Shared" } scritto come un JSON sia accettato

    String json = "{" +
      "\"type\": \"record\", " +
      "\"name\": \"Container\", " +
      "\"fields\": [" +
      "  {\"name\": \"f\", \"type\": {\"type\": \"Shared\"}}" +
      "]" +
      "}";

    Schema schema = parser.parse(json);

    assertNotNull("Lo schema del campo non deve essere null", schema.getField("f").schema());
    assertEquals("Shared", schema.getField("f").schema().getName());
  }
}
